// MQO Dispatcher — generated by Batch Code Generator
// Builds shared components, then dispatches per-query tails.
//
// Usage:
//   ./mqo --all                          Run full 22-query batch
//   ./mqo --query Q3                     Run only Q3
//   ./mqo --list                         Print query IDs and shared deps
//   ./mqo --gendb-dir <dir>              Override storage path
//   ./mqo --output-dir <dir>             Override result output (default ./results)

#include "mqo_profile.hpp"
#include "shared/mqo_io.hpp"
#include "shared/scan_lineitem_full.hpp"
#include "shared/scan_lineitem_shipdate_1994.hpp"
#include "shared/scan_lineitem_shipdate_1995_1996.hpp"
#include "shared/hash_orders_by_orderkey.hpp"
#include "shared/hash_customer_by_custkey.hpp"
#include "shared/hash_supplier_by_suppkey.hpp"

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <functional>
#include <set>
#include <string>
#include <vector>
#include <sys/stat.h>
#include <sys/types.h>
#include <omp.h>

// ---------------------------------------------------------------------------
// Per-query tail entry points (implemented in queries/qN.cpp)
// ---------------------------------------------------------------------------
namespace mqo::tails {
void run_Q1 (const mqo::Context& ctx);
void run_Q2 (const mqo::Context& ctx);
void run_Q3 (const mqo::Context& ctx);
void run_Q4 (const mqo::Context& ctx);
void run_Q5 (const mqo::Context& ctx);
void run_Q6 (const mqo::Context& ctx);
void run_Q7 (const mqo::Context& ctx);
void run_Q8 (const mqo::Context& ctx);
void run_Q9 (const mqo::Context& ctx);
void run_Q10(const mqo::Context& ctx);
void run_Q11(const mqo::Context& ctx);
void run_Q12(const mqo::Context& ctx);
void run_Q13(const mqo::Context& ctx);
void run_Q14(const mqo::Context& ctx);
void run_Q15(const mqo::Context& ctx);
void run_Q16(const mqo::Context& ctx);
void run_Q17(const mqo::Context& ctx);
void run_Q18(const mqo::Context& ctx);
void run_Q19(const mqo::Context& ctx);
void run_Q20(const mqo::Context& ctx);
void run_Q21(const mqo::Context& ctx);
void run_Q22(const mqo::Context& ctx);
}  // namespace mqo::tails

// ---------------------------------------------------------------------------
// Shared-component enum + build dispatch
// ---------------------------------------------------------------------------
enum class SC {
    SCAN_LINEITEM_FULL,
    SCAN_LINEITEM_SHIPDATE_1994,
    SCAN_LINEITEM_SHIPDATE_1995_1996,
    HASH_ORDERS_BY_ORDERKEY,
    HASH_CUSTOMER_BY_CUSTKEY,
    HASH_SUPPLIER_BY_SUPPKEY,
};

static const char* sc_name(SC c) {
    switch (c) {
        case SC::SCAN_LINEITEM_FULL:              return "scan_lineitem_full";
        case SC::SCAN_LINEITEM_SHIPDATE_1994:     return "scan_lineitem_shipdate_1994";
        case SC::SCAN_LINEITEM_SHIPDATE_1995_1996:return "scan_lineitem_shipdate_1995_1996";
        case SC::HASH_ORDERS_BY_ORDERKEY:         return "hash_orders_by_orderkey";
        case SC::HASH_CUSTOMER_BY_CUSTKEY:        return "hash_customer_by_custkey";
        case SC::HASH_SUPPLIER_BY_SUPPKEY:        return "hash_supplier_by_suppkey";
    }
    return "unknown";
}

static void build_component(const mqo::Context& ctx, SC c) {
    switch (c) {
        case SC::SCAN_LINEITEM_FULL:
            mqo::shared::scan_lineitem_full::get_columns(ctx);
            break;
        case SC::SCAN_LINEITEM_SHIPDATE_1994:
            mqo::shared::scan_lineitem_shipdate_1994::build(ctx);
            break;
        case SC::SCAN_LINEITEM_SHIPDATE_1995_1996:
            mqo::shared::scan_lineitem_shipdate_1995_1996::build(ctx);
            break;
        case SC::HASH_ORDERS_BY_ORDERKEY:
            mqo::shared::hash_orders_by_orderkey::build(ctx);
            break;
        case SC::HASH_CUSTOMER_BY_CUSTKEY:
            mqo::shared::hash_customer_by_custkey::build(ctx);
            break;
        case SC::HASH_SUPPLIER_BY_SUPPKEY:
            mqo::shared::hash_supplier_by_suppkey::build(ctx);
            break;
    }
}

// ---------------------------------------------------------------------------
// Per-query metadata (dependency list + tail function pointer)
// ---------------------------------------------------------------------------
using TailFn = void(*)(const mqo::Context&);

struct QueryInfo {
    const char* id;
    TailFn      tail;
    std::vector<SC> deps;
};

static const QueryInfo QUERIES[] = {
    {"Q1",  mqo::tails::run_Q1,  {SC::SCAN_LINEITEM_FULL}},
    {"Q2",  mqo::tails::run_Q2,  {SC::HASH_SUPPLIER_BY_SUPPKEY}},
    {"Q3",  mqo::tails::run_Q3,  {SC::SCAN_LINEITEM_FULL, SC::HASH_ORDERS_BY_ORDERKEY, SC::HASH_CUSTOMER_BY_CUSTKEY}},
    {"Q4",  mqo::tails::run_Q4,  {SC::SCAN_LINEITEM_FULL}},
    {"Q5",  mqo::tails::run_Q5,  {SC::SCAN_LINEITEM_FULL, SC::HASH_ORDERS_BY_ORDERKEY, SC::HASH_CUSTOMER_BY_CUSTKEY, SC::HASH_SUPPLIER_BY_SUPPKEY}},
    {"Q6",  mqo::tails::run_Q6,  {SC::SCAN_LINEITEM_FULL, SC::SCAN_LINEITEM_SHIPDATE_1994}},
    {"Q7",  mqo::tails::run_Q7,  {SC::SCAN_LINEITEM_FULL, SC::HASH_ORDERS_BY_ORDERKEY, SC::HASH_CUSTOMER_BY_CUSTKEY, SC::HASH_SUPPLIER_BY_SUPPKEY, SC::SCAN_LINEITEM_SHIPDATE_1995_1996}},
    {"Q8",  mqo::tails::run_Q8,  {SC::SCAN_LINEITEM_FULL, SC::HASH_ORDERS_BY_ORDERKEY, SC::HASH_CUSTOMER_BY_CUSTKEY, SC::HASH_SUPPLIER_BY_SUPPKEY}},
    {"Q9",  mqo::tails::run_Q9,  {SC::SCAN_LINEITEM_FULL, SC::HASH_ORDERS_BY_ORDERKEY, SC::HASH_SUPPLIER_BY_SUPPKEY}},
    {"Q10", mqo::tails::run_Q10, {SC::SCAN_LINEITEM_FULL, SC::HASH_ORDERS_BY_ORDERKEY, SC::HASH_CUSTOMER_BY_CUSTKEY}},
    {"Q11", mqo::tails::run_Q11, {SC::HASH_SUPPLIER_BY_SUPPKEY}},
    {"Q12", mqo::tails::run_Q12, {SC::SCAN_LINEITEM_FULL, SC::HASH_ORDERS_BY_ORDERKEY}},
    {"Q13", mqo::tails::run_Q13, {SC::HASH_CUSTOMER_BY_CUSTKEY}},
    {"Q14", mqo::tails::run_Q14, {SC::SCAN_LINEITEM_FULL, SC::SCAN_LINEITEM_SHIPDATE_1995_1996}},
    {"Q15", mqo::tails::run_Q15, {SC::SCAN_LINEITEM_FULL, SC::HASH_SUPPLIER_BY_SUPPKEY, SC::SCAN_LINEITEM_SHIPDATE_1995_1996}},
    {"Q16", mqo::tails::run_Q16, {}},
    {"Q17", mqo::tails::run_Q17, {SC::SCAN_LINEITEM_FULL}},
    {"Q18", mqo::tails::run_Q18, {SC::SCAN_LINEITEM_FULL, SC::HASH_ORDERS_BY_ORDERKEY, SC::HASH_CUSTOMER_BY_CUSTKEY}},
    {"Q19", mqo::tails::run_Q19, {SC::SCAN_LINEITEM_FULL}},
    {"Q20", mqo::tails::run_Q20, {SC::SCAN_LINEITEM_FULL, SC::SCAN_LINEITEM_SHIPDATE_1994, SC::HASH_SUPPLIER_BY_SUPPKEY}},
    {"Q21", mqo::tails::run_Q21, {SC::SCAN_LINEITEM_FULL, SC::HASH_ORDERS_BY_ORDERKEY, SC::HASH_SUPPLIER_BY_SUPPKEY}},
    {"Q22", mqo::tails::run_Q22, {}},
};
static constexpr int N_QUERIES = 22;

static const QueryInfo* find_query(const char* id) {
    for (int i = 0; i < N_QUERIES; ++i) {
        if (std::strcmp(QUERIES[i].id, id) == 0) return &QUERIES[i];
    }
    return nullptr;
}

// ---------------------------------------------------------------------------
// Build shared components for a subset of queries
// ---------------------------------------------------------------------------
static void build_shared_subset(const mqo::Context& ctx, const std::set<SC>& needed) {
    MQO_TIME_PHASE("build_shared_subset");

    // Tier 1: hash_customer, hash_supplier (independent, can run in parallel)
    bool need_cust = needed.count(SC::HASH_CUSTOMER_BY_CUSTKEY) > 0;
    bool need_supp = needed.count(SC::HASH_SUPPLIER_BY_SUPPKEY) > 0;
    if (need_cust && need_supp) {
        #pragma omp parallel sections
        {
            #pragma omp section
            { build_component(ctx, SC::HASH_CUSTOMER_BY_CUSTKEY); }
            #pragma omp section
            { build_component(ctx, SC::HASH_SUPPLIER_BY_SUPPKEY); }
        }
    } else {
        if (need_cust) build_component(ctx, SC::HASH_CUSTOMER_BY_CUSTKEY);
        if (need_supp) build_component(ctx, SC::HASH_SUPPLIER_BY_SUPPKEY);
    }

    // Tier 2: hash_orders
    if (needed.count(SC::HASH_ORDERS_BY_ORDERKEY))
        build_component(ctx, SC::HASH_ORDERS_BY_ORDERKEY);

    // Tier 3: scan_lineitem_full (mmap init)
    if (needed.count(SC::SCAN_LINEITEM_FULL))
        build_component(ctx, SC::SCAN_LINEITEM_FULL);

    // Tier 4: filtered scans (derived from scan_lineitem_full, can be parallel)
    bool need_1994     = needed.count(SC::SCAN_LINEITEM_SHIPDATE_1994) > 0;
    bool need_1995_96  = needed.count(SC::SCAN_LINEITEM_SHIPDATE_1995_1996) > 0;
    if (need_1994 && need_1995_96) {
        #pragma omp parallel sections
        {
            #pragma omp section
            { build_component(ctx, SC::SCAN_LINEITEM_SHIPDATE_1994); }
            #pragma omp section
            { build_component(ctx, SC::SCAN_LINEITEM_SHIPDATE_1995_1996); }
        }
    } else {
        if (need_1994)    build_component(ctx, SC::SCAN_LINEITEM_SHIPDATE_1994);
        if (need_1995_96) build_component(ctx, SC::SCAN_LINEITEM_SHIPDATE_1995_1996);
    }
}

// ---------------------------------------------------------------------------
// Build ALL shared components (full batch, follows skeleton execution_order)
// ---------------------------------------------------------------------------
static void build_all_shared(const mqo::Context& ctx) {
    MQO_TIME_PHASE("build_all_shared");

    // Tier 1: hash_customer_by_custkey, hash_supplier_by_suppkey (parallel)
    #pragma omp parallel sections
    {
        #pragma omp section
        { mqo::shared::hash_customer_by_custkey::build(ctx); }
        #pragma omp section
        { mqo::shared::hash_supplier_by_suppkey::build(ctx); }
    }

    // Tier 2: hash_orders_by_orderkey
    mqo::shared::hash_orders_by_orderkey::build(ctx);

    // Tier 3: scan_lineitem_full (mmap init — warms page cache)
    mqo::shared::scan_lineitem_full::get_columns(ctx);

    // Tier 4: filtered scans (parallel, derived from mmap'd lineitem)
    #pragma omp parallel sections
    {
        #pragma omp section
        { mqo::shared::scan_lineitem_shipdate_1994::build(ctx); }
        #pragma omp section
        { mqo::shared::scan_lineitem_shipdate_1995_1996::build(ctx); }
    }
}

// ---------------------------------------------------------------------------
// Ensure directory exists
// ---------------------------------------------------------------------------
static void ensure_dir(const std::string& path) {
    ::mkdir(path.c_str(), 0755);
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------
int main(int argc, char** argv) {
    MQO_TIME_DISPATCHER("dispatcher_total");

    // Defaults
    std::string gendb_dir  = "/home/jl4492/GenDB/output/tpc-h-sf10/storage";
    std::string output_dir = "./results";
    bool run_all     = false;
    bool run_list    = false;
    const char* single_qid = nullptr;

    // Parse arguments
    for (int i = 1; i < argc; ++i) {
        if (std::strcmp(argv[i], "--all") == 0) {
            run_all = true;
        } else if (std::strcmp(argv[i], "--list") == 0) {
            run_list = true;
        } else if (std::strcmp(argv[i], "--query") == 0) {
            if (++i >= argc) {
                std::fprintf(stderr, "Error: --query requires an argument\n");
                return 1;
            }
            single_qid = argv[i];
        } else if (std::strcmp(argv[i], "--gendb-dir") == 0) {
            if (++i >= argc) {
                std::fprintf(stderr, "Error: --gendb-dir requires an argument\n");
                return 1;
            }
            gendb_dir = argv[i];
        } else if (std::strcmp(argv[i], "--output-dir") == 0) {
            if (++i >= argc) {
                std::fprintf(stderr, "Error: --output-dir requires an argument\n");
                return 1;
            }
            output_dir = argv[i];
        } else {
            std::fprintf(stderr, "Error: unknown option '%s'\n", argv[i]);
            return 1;
        }
    }

    // --list mode
    if (run_list) {
        for (int i = 0; i < N_QUERIES; ++i) {
            std::printf("%-4s:", QUERIES[i].id);
            for (size_t d = 0; d < QUERIES[i].deps.size(); ++d) {
                std::printf(" %s%s", sc_name(QUERIES[i].deps[d]),
                            d + 1 < QUERIES[i].deps.size() ? "," : "");
            }
            if (QUERIES[i].deps.empty()) std::printf(" (none)");
            std::printf("\n");
        }
        return 0;
    }

    if (!run_all && !single_qid) {
        std::fprintf(stderr,
            "Usage: %s --all | --query <QID> | --list\n"
            "  --gendb-dir <dir>   Storage path (default: built-in)\n"
            "  --output-dir <dir>  Result output (default: ./results)\n",
            argv[0]);
        return 1;
    }

    // Build context
    mqo::Context ctx;
    ctx.gendb_dir  = gendb_dir;
    ctx.output_dir = output_dir;
    ensure_dir(output_dir);

    // --query Qi mode
    if (single_qid) {
        const QueryInfo* qi = find_query(single_qid);
        if (!qi) {
            std::fprintf(stderr, "Error: unknown query '%s'\n", single_qid);
            return 2;
        }

        // Build only the shared components this query needs
        std::set<SC> needed(qi->deps.begin(), qi->deps.end());
        if (!needed.empty()) {
            build_shared_subset(ctx, needed);
        }

        // Run the tail
        {
            MQO_TIME_PHASE("tail_execution");
            qi->tail(ctx);
        }

        MQO_PROFILE_FLUSH("profile.json");
        return 0;
    }

    // --all mode: build all shared, then run all tails in parallel
    build_all_shared(ctx);

    {
        MQO_TIME_PHASE("all_tails");
        static const TailFn TAIL_FNS[N_QUERIES] = {
            mqo::tails::run_Q1,  mqo::tails::run_Q2,  mqo::tails::run_Q3,
            mqo::tails::run_Q4,  mqo::tails::run_Q5,  mqo::tails::run_Q6,
            mqo::tails::run_Q7,  mqo::tails::run_Q8,  mqo::tails::run_Q9,
            mqo::tails::run_Q10, mqo::tails::run_Q11, mqo::tails::run_Q12,
            mqo::tails::run_Q13, mqo::tails::run_Q14, mqo::tails::run_Q15,
            mqo::tails::run_Q16, mqo::tails::run_Q17, mqo::tails::run_Q18,
            mqo::tails::run_Q19, mqo::tails::run_Q20, mqo::tails::run_Q21,
            mqo::tails::run_Q22,
        };

        #pragma omp parallel for schedule(dynamic, 1)
        for (int i = 0; i < N_QUERIES; ++i) {
            TAIL_FNS[i](ctx);
        }
    }

    MQO_PROFILE_FLUSH("profile.json");
    return 0;
}
