// MQO Batch Dispatcher — generated by MQO Batch Code Generator.
// Builds shared components (mmap-based), then dispatches per-query tails.
//
// Usage:
//   ./mqo --all                  Run all 22 queries
//   ./mqo --query Q3             Run single query Q3
//   ./mqo --list                 List queries and shared deps
//   ./mqo --output-dir <dir>     Result directory (default: ./results)
//   ./mqo --data-dir <dir>       GenDB storage directory

#include "mqo_profile.hpp"
#include "shared/scan_lineitem_full.hpp"
#include "shared/scan_orders_full.hpp"
#include "shared/hash_customer_by_custkey.hpp"
#include "shared/hash_part_by_partkey.hpp"
#include "shared/scan_partsupp_full.hpp"
#include "shared/hash_supplier_by_suppkey.hpp"

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <sys/stat.h>
#include <sys/types.h>

// ====================================================================
// Global shared component outputs
// ====================================================================
static mqo::shared::scan_lineitem_full::Columns      g_lineitem{};
static mqo::shared::scan_orders_full::Output          g_orders{};
static mqo::shared::hash_customer_by_custkey::Output  g_customer{};
static mqo::shared::hash_part_by_partkey::Output      g_part{};
static mqo::shared::scan_partsupp_full::Output        g_partsupp{};
static mqo::shared::hash_supplier_by_suppkey::Output  g_supplier{};

enum CompIdx : int {
    IDX_LINEITEM = 0, IDX_ORDERS = 1, IDX_CUSTOMER = 2,
    IDX_PART = 3, IDX_PARTSUPP = 4, IDX_SUPPLIER = 5,
    NUM_COMPONENTS = 6
};
static bool g_loaded[NUM_COMPONENTS] = {};

// ====================================================================
// Getter definitions (declared in shared/*.hpp, resolved at link time)
// ====================================================================
namespace mqo { namespace shared { namespace scan_lineitem_full {
    const Columns& get() { return g_lineitem; }
}}}
namespace mqo { namespace shared { namespace scan_orders_full {
    const Output& get() { return g_orders; }
}}}
namespace mqo { namespace shared { namespace hash_customer_by_custkey {
    const Output& get() { return g_customer; }
}}}
namespace mqo { namespace shared { namespace hash_part_by_partkey {
    const Output& get() { return g_part; }
}}}
namespace mqo { namespace shared { namespace scan_partsupp_full {
    const Output& get() { return g_partsupp; }
}}}
namespace mqo { namespace shared { namespace hash_supplier_by_suppkey {
    const Output& get() { return g_supplier; }
}}}

// ====================================================================
// Build a single shared component (idempotent)
// ====================================================================
static void build_component(const char* id, const mqo::Context& ctx) {
    if (std::strcmp(id, "scan_lineitem_full") == 0 && !g_loaded[IDX_LINEITEM]) {
        mqo::shared::scan_lineitem_full::run_callback(ctx,
            [](const mqo::shared::scan_lineitem_full::Columns& c) { g_lineitem = c; });
        g_loaded[IDX_LINEITEM] = true;
    } else if (std::strcmp(id, "scan_orders_full") == 0 && !g_loaded[IDX_ORDERS]) {
        g_orders = mqo::shared::scan_orders_full::build(ctx);
        g_loaded[IDX_ORDERS] = true;
    } else if (std::strcmp(id, "hash_customer_by_custkey") == 0 && !g_loaded[IDX_CUSTOMER]) {
        g_customer = mqo::shared::hash_customer_by_custkey::build(ctx);
        g_loaded[IDX_CUSTOMER] = true;
    } else if (std::strcmp(id, "hash_part_by_partkey") == 0 && !g_loaded[IDX_PART]) {
        g_part = mqo::shared::hash_part_by_partkey::build(ctx);
        g_loaded[IDX_PART] = true;
    } else if (std::strcmp(id, "scan_partsupp_full") == 0 && !g_loaded[IDX_PARTSUPP]) {
        g_partsupp = mqo::shared::scan_partsupp_full::build(ctx);
        g_loaded[IDX_PARTSUPP] = true;
    } else if (std::strcmp(id, "hash_supplier_by_suppkey") == 0 && !g_loaded[IDX_SUPPLIER]) {
        g_supplier = mqo::shared::hash_supplier_by_suppkey::build(ctx);
        g_loaded[IDX_SUPPLIER] = true;
    }
}

// ====================================================================
// Per-query tail entry points (implemented in queries/qN.cpp)
// ====================================================================
namespace mqo { namespace tails {
    void run_Q1 (const Context& ctx);
    void run_Q2 (const Context& ctx);
    void run_Q3 (const Context& ctx);
    void run_Q4 (const Context& ctx);
    void run_Q5 (const Context& ctx);
    void run_Q6 (const Context& ctx);
    void run_Q7 (const Context& ctx);
    void run_Q8 (const Context& ctx);
    void run_Q9 (const Context& ctx);
    void run_Q10(const Context& ctx);
    void run_Q11(const Context& ctx);
    void run_Q12(const Context& ctx);
    void run_Q13(const Context& ctx);
    void run_Q14(const Context& ctx);
    void run_Q15(const Context& ctx);
    void run_Q16(const Context& ctx);
    void run_Q17(const Context& ctx);
    void run_Q18(const Context& ctx);
    void run_Q19(const Context& ctx);
    void run_Q20(const Context& ctx);
    void run_Q21(const Context& ctx);
    void run_Q22(const Context& ctx);
}}

// ====================================================================
// Query registry (embedded manifest — consistent with manifest.json)
// ====================================================================
using TailFn = void(*)(const mqo::Context&);

struct QueryEntry {
    const char* id;
    TailFn      fn;
    const char* deps[6];  // shared component deps, null-terminated (max 5 deps)
};

static constexpr int NUM_QUERIES = 22;

static const QueryEntry g_queries[NUM_QUERIES] = {
    {"Q1",  mqo::tails::run_Q1,
     {"scan_lineitem_full", nullptr}},
    {"Q2",  mqo::tails::run_Q2,
     {"hash_part_by_partkey","scan_partsupp_full","hash_supplier_by_suppkey", nullptr}},
    {"Q3",  mqo::tails::run_Q3,
     {"scan_lineitem_full","scan_orders_full","hash_customer_by_custkey", nullptr}},
    {"Q4",  mqo::tails::run_Q4,
     {"scan_orders_full", nullptr}},
    {"Q5",  mqo::tails::run_Q5,
     {"scan_lineitem_full","scan_orders_full","hash_customer_by_custkey","hash_supplier_by_suppkey", nullptr}},
    {"Q6",  mqo::tails::run_Q6,
     {"scan_lineitem_full", nullptr}},
    {"Q7",  mqo::tails::run_Q7,
     {"scan_lineitem_full","scan_orders_full","hash_customer_by_custkey","hash_supplier_by_suppkey", nullptr}},
    {"Q8",  mqo::tails::run_Q8,
     {"scan_lineitem_full","scan_orders_full","hash_customer_by_custkey","hash_part_by_partkey","hash_supplier_by_suppkey", nullptr}},
    {"Q9",  mqo::tails::run_Q9,
     {"scan_orders_full","hash_part_by_partkey","scan_partsupp_full","hash_supplier_by_suppkey", nullptr}},
    {"Q10", mqo::tails::run_Q10,
     {"scan_lineitem_full","scan_orders_full","hash_customer_by_custkey", nullptr}},
    {"Q11", mqo::tails::run_Q11,
     {"scan_partsupp_full","hash_supplier_by_suppkey", nullptr}},
    {"Q12", mqo::tails::run_Q12,
     {"scan_lineitem_full","scan_orders_full", nullptr}},
    {"Q13", mqo::tails::run_Q13,
     {"scan_orders_full","hash_customer_by_custkey", nullptr}},
    {"Q14", mqo::tails::run_Q14,
     {"scan_lineitem_full","hash_part_by_partkey", nullptr}},
    {"Q15", mqo::tails::run_Q15,
     {"scan_lineitem_full","hash_supplier_by_suppkey", nullptr}},
    {"Q16", mqo::tails::run_Q16,
     {"hash_part_by_partkey","scan_partsupp_full","hash_supplier_by_suppkey", nullptr}},
    {"Q17", mqo::tails::run_Q17,
     {"hash_part_by_partkey", nullptr}},
    {"Q18", mqo::tails::run_Q18,
     {"scan_lineitem_full","scan_orders_full","hash_customer_by_custkey", nullptr}},
    {"Q19", mqo::tails::run_Q19,
     {"hash_part_by_partkey", nullptr}},
    {"Q20", mqo::tails::run_Q20,
     {"hash_part_by_partkey","scan_partsupp_full","hash_supplier_by_suppkey", nullptr}},
    {"Q21", mqo::tails::run_Q21,
     {"scan_orders_full","hash_supplier_by_suppkey", nullptr}},
    {"Q22", mqo::tails::run_Q22,
     {"scan_orders_full","hash_customer_by_custkey", nullptr}},
};

// ====================================================================
// Helpers
// ====================================================================
static void ensure_dir(const std::string& path) {
    ::mkdir(path.c_str(), 0755);
}

static const QueryEntry* find_query(const char* id) {
    for (int i = 0; i < NUM_QUERIES; ++i) {
        if (std::strcmp(g_queries[i].id, id) == 0) return &g_queries[i];
    }
    return nullptr;
}

static void print_usage() {
    std::fprintf(stderr,
        "Usage: ./mqo [OPTIONS]\n"
        "  --all                 Run all 22 TPC-H queries\n"
        "  --query <QID>         Run a single query (e.g. Q3)\n"
        "  --list                List supported queries and shared deps\n"
        "  --output-dir <dir>    Result directory (default: ./results)\n"
        "  --data-dir <dir>      GenDB binary storage directory (default: ../../../storage)\n");
}

// ====================================================================
// Main
// ====================================================================
int main(int argc, char** argv) {
    // ----------------------------------------------------------------
    // Argument parsing
    // ----------------------------------------------------------------
    std::string data_dir   = "../../../storage";
    std::string output_dir = "./results";
    bool        run_all    = false;
    const char* single_qid = nullptr;
    bool        list_mode  = false;

    for (int i = 1; i < argc; ++i) {
        if (std::strcmp(argv[i], "--all") == 0) {
            run_all = true;
        } else if (std::strcmp(argv[i], "--query") == 0 && i + 1 < argc) {
            single_qid = argv[++i];
        } else if (std::strcmp(argv[i], "--list") == 0) {
            list_mode = true;
        } else if (std::strcmp(argv[i], "--output-dir") == 0 && i + 1 < argc) {
            output_dir = argv[++i];
        } else if (std::strcmp(argv[i], "--data-dir") == 0 && i + 1 < argc) {
            data_dir = argv[++i];
        } else {
            std::fprintf(stderr, "ERROR: Unknown option '%s'\n", argv[i]);
            print_usage();
            return 1;
        }
    }

    // ----------------------------------------------------------------
    // --list: print queries and exit
    // ----------------------------------------------------------------
    if (list_mode) {
        for (int i = 0; i < NUM_QUERIES; ++i) {
            std::printf("%s:", g_queries[i].id);
            for (int j = 0; g_queries[i].deps[j]; ++j) {
                std::printf("%s%s", (j == 0) ? " " : ", ", g_queries[i].deps[j]);
            }
            std::printf("\n");
        }
        return 0;
    }

    if (!run_all && !single_qid) {
        std::fprintf(stderr, "ERROR: Specify --all, --query <QID>, or --list\n");
        print_usage();
        return 1;
    }

    // ----------------------------------------------------------------
    // Build context
    // ----------------------------------------------------------------
    mqo::Context ctx;
    ctx.gendb_dir  = data_dir;
    ctx.output_dir = output_dir;
    ensure_dir(output_dir);

    // ----------------------------------------------------------------
    // --query Qi: build minimal subset, run single tail
    // ----------------------------------------------------------------
    if (single_qid) {
        const QueryEntry* qe = find_query(single_qid);
        if (!qe) {
            std::fprintf(stderr, "ERROR: Unknown query '%s'. Use --list to see valid IDs.\n",
                         single_qid);
            return 2;
        }
        {
            MQO_TIME_DISPATCHER("dispatcher_total");
            {
                MQO_TIME_PHASE("single_query_shared_build");
                for (int j = 0; qe->deps[j]; ++j) {
                    build_component(qe->deps[j], ctx);
                }
            }
            {
                MQO_TIME_PHASE("single_query_tail");
                qe->fn(ctx);
            }
        }
        MQO_PROFILE_FLUSH("profile.json");
        return 0;
    }

    // ----------------------------------------------------------------
    // --all: execute batch skeleton (5 tiers)
    // ----------------------------------------------------------------
    {
        MQO_TIME_DISPATCHER("dispatcher_total");

        // Tier 1: hash builds (parallel — small dim tables, I/O-bound)
        {
            MQO_TIME_PHASE("tier1_hash_builds");
            #pragma omp parallel sections
            {
                #pragma omp section
                build_component("hash_supplier_by_suppkey", ctx);
                #pragma omp section
                build_component("hash_customer_by_custkey", ctx);
                #pragma omp section
                build_component("hash_part_by_partkey", ctx);
            }
        }

        // Tier 2: partsupp full scan (8M rows, 192MB)
        {
            MQO_TIME_PHASE("tier2_scan_partsupp");
            build_component("scan_partsupp_full", ctx);
        }

        // Tier 3: orders full scan (15M rows, 600MB)
        {
            MQO_TIME_PHASE("tier3_scan_orders");
            build_component("scan_orders_full", ctx);
        }

        // Tier 4: lineitem full scan — callback mode stores mmap'd columns
        // in the global for tail access (60M rows, 4.2GB)
        {
            MQO_TIME_PHASE("tier4_scan_lineitem");
            build_component("scan_lineitem_full", ctx);
        }

        // Tier 5: all query tails in parallel (skeleton marks all as same tier)
        {
            MQO_TIME_PHASE("tier5_tails");
            #pragma omp parallel for schedule(dynamic)
            for (int i = 0; i < NUM_QUERIES; ++i) {
                g_queries[i].fn(ctx);
            }
        }
    }

    MQO_PROFILE_FLUSH("profile.json");
    return 0;
}
