/**
 * GenDB runtime hyperparameter configuration.
 * Defaults can be overridden via CLI args in the orchestrator.
 *
 * Structure:
 *   - Top level: pipeline settings (provider-agnostic)
 *   - providers.<name>: provider-specific settings (model, effort levels, pricing)
 */

export const defaults = {
  // --- Pipeline settings (provider-agnostic) ---
  agentProvider: "claude",  // "claude" or "codex" — select the underlying agent SDK
  targetBenchmark: "tpc-h", // "tpc-h" / "sec-edgar"
  scaleFactor: 10,          // 10 for tpc-h, 3 for sec-edgar
  optimizationTarget: "hot",  // "hot" (optimize avg hot runs) or "cold" (optimize cold run)
  maxOptimizationIterations: 5,
  stallThreshold: 5,        // consecutive non-improving iterations before adaptive stop
  maxConcurrentQueries: 22,
  queryExecutionTimeoutSec: 300, // per-query binary execution timeout (seconds)
  optimizationRuns: 3,      // per-execution: all runs same mode (hot or cold)
  correctnessFailureCap: 3, // consecutive correctness failures before escalating
  useSkills: false,  // Enable native Claude skills from .claude/skills/ (requires memory system)

  // --- Memory system v3 (provider-agnostic, experimental) ---
  // 6-layer HAG: L0 instances → L1 templates → L2 patterns → L3 operators → L4 strategies → L5 principles
  // L0/L1: HAG (structural retrieval via SQL features), L2-L5: Skills (semantic retrieval via Claude)
  // Enable with --memory-dir <path> on CLI
  memoryDir: null,              // Path to memory directory (null = disabled)
  skillsDir: ".claude/skills",  // Path to skills directory (auto-generated by Memory Manager)
  memory: {
    structuralMatchMinScore: 0.5,     // L1 match threshold (exact > 0.9, structural >= 0.5)
    maxPreInjectionTokens: 4000,
    differentialThreshold: 0.2,       // 20% improvement = SIGNIFICANT_IMPROVEMENT
    layers: {
      L0: { name: "instances", storage: "hag" },
      L1: { name: "templates", storage: "hag" },
      L2: { name: "patterns", storage: "skills" },
      L3: { name: "operators", storage: "skills" },
      L4: { name: "strategies", storage: "skills" },
      L5: { name: "principles", storage: "skills" },
    },
  },

  // --- Agent timeouts (provider-agnostic) ---
  agentTimeoutMs: 30 * 60 * 1000, // 30 minutes per agent call
  agentTimeoutOverrides: {
    storage_designer: 45 * 60 * 1000,           // 45 minutes — includes data ingestion + index building
    query_optimizer: 30 * 60 * 1000,            // 30 minutes
    // MQO-mode agents (see src/gendb/orchestrator/mqo.mjs)
    mqo_batch_code_generator: 60 * 60 * 1000,   // 60 minutes — large multi-file emission
    mqo_global_integrator: 30 * 60 * 1000,      // 30 minutes
  },

  // --- MQO (Multiple Query Optimization) mode (provider-agnostic) ---
  // Enabled via `--optimization-mode mqo` CLI flag. See plan file for full design.
  mqo: {
    enabled: false,                    // set to true when --optimization-mode mqo
    analyzerThreshold: 30,             // batch size cutoff between small-batch (single-agent) and large-batch (Surveyor→Clusters→Integrator) paths
    clustering: {
      targetClustersPerLarge: 8,       // rough target cluster count in large-batch path
      minSharedCandidates: 2,          // K: min shared candidate components for co-clustering
    },
    optimizer: {
      maxIterations: 5,
      stallThreshold: 5,
      minImprovement: 0.02,            // 2% relative batch-total improvement to accept
      regressionSlack: 0.05,           // max per-query regression tolerated for non-tail edits (5%)
      compilationRetryCap: 2,
    },
    profile: {
      runsPerMeasurement: 3,           // mirrors defaults.optimizationRuns idiom for hot-mode averaging
    },
  },

  // --- Single-agent mode (provider-agnostic parts) ---
  singleAgent: {
    timeoutMs: 120 * 60 * 1000,  // 2 hours
    promptVariant: "high-level",  // "high-level" or "guided"
    maxOptimizationIterations: 5,
  },

  // --- Provider-specific settings ---
  providers: {
    claude: {
      model: "opus",
      agentModels: {
        workload_analyzer: "opus",
        storage_designer: "opus",
        query_planner: "opus",
        code_generator: "opus",
        query_optimizer: "opus",
        memory_manager: "opus",
        // MQO-mode agents
        mqo_analyzer_small: "opus",
        mqo_surveyor: "opus",
        mqo_cluster_analyzer: "opus",
        mqo_global_integrator: "opus",
        mqo_skeleton_planner: "opus",
        mqo_batch_code_generator: "opus",
        mqo_optimizer: "opus",
      },
      // Claude effort: "low" | "medium" | "high" | "max" (max = Opus only)
      agentEffortLevels: {
        workload_analyzer: "low",
        storage_designer: "medium",
        query_planner: "medium",
        code_generator: "medium",
        query_optimizer: "medium",
        memory_manager: "medium",
        // MQO-mode agents
        mqo_analyzer_small: "medium",
        mqo_surveyor: "low",              // tool-driven breadth walk, shallow reasoning
        mqo_cluster_analyzer: "medium",
        mqo_global_integrator: "medium",
        mqo_skeleton_planner: "medium",
        mqo_batch_code_generator: "high", // large output surface
        mqo_optimizer: "medium",
      },
      escalationModel: "opus",
      escalationEffortLevel: "high",
      singleAgent: {
        model: "opus",
        effortLevel: "medium",
      },
    },
    codex: {
      model: "gpt-5.4",
      agentModels: {
        workload_analyzer: "gpt-5.4",
        storage_designer: "gpt-5.4",
        query_planner: "gpt-5.4",
        code_generator: "gpt-5.4",
        query_optimizer: "gpt-5.4",
        memory_manager: "gpt-5.4",
        // MQO-mode agents
        mqo_analyzer_small: "gpt-5.4",
        mqo_surveyor: "gpt-5.4",
        mqo_cluster_analyzer: "gpt-5.4",
        mqo_global_integrator: "gpt-5.4",
        mqo_skeleton_planner: "gpt-5.4",
        mqo_batch_code_generator: "gpt-5.4",
        mqo_optimizer: "gpt-5.4",
      },
      // Codex effort: "minimal" | "low" | "medium" | "high" | "xhigh"
      agentEffortLevels: {
        workload_analyzer: "low",
        storage_designer: "medium",
        query_planner: "medium",
        code_generator: "medium",
        query_optimizer: "medium",
        memory_manager: "medium",
        // MQO-mode agents
        mqo_analyzer_small: "medium",
        mqo_surveyor: "low",
        mqo_cluster_analyzer: "medium",
        mqo_global_integrator: "medium",
        mqo_skeleton_planner: "medium",
        mqo_batch_code_generator: "high",
        mqo_optimizer: "medium",
      },
      escalationModel: "gpt-5.4",
      escalationEffortLevel: "high",
      singleAgent: {
        model: "gpt-5.4",
        effortLevel: "medium",
      },
    },
  },
};

/**
 * Get the provider-specific config for the active (or given) provider.
 */
export function getProviderConfig(providerName) {
  const name = providerName || defaults.agentProvider;
  const config = defaults.providers[name];
  if (!config) {
    throw new Error(`No provider config for "${name}". Available: ${Object.keys(defaults.providers).join(", ")}`);
  }
  return config;
}
