#pragma once

// MQO I/O helpers — inline memory-mapped column access for GenDB binary format.
// Generated by MQO Batch Code Generator. Do NOT depend on external utility headers.

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <fcntl.h>
#include <string>
#include <string_view>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>
#include <vector>

namespace mqo {

// Ambient context passed to shared components and tails.
struct Context {
    std::string gendb_dir;   // path to GenDB binary storage directory
    std::string output_dir;  // path to result CSV output directory
};

namespace io {

// ---------------------------------------------------------------------------
// Row count
// ---------------------------------------------------------------------------
inline size_t read_row_count(const std::string& table_dir) {
    std::string path = table_dir + "/meta.txt";
    FILE* f = std::fopen(path.c_str(), "r");
    if (!f) {
        std::fprintf(stderr, "ERROR: Cannot open %s\n", path.c_str());
        std::exit(1);
    }
    size_t n = 0;
    if (std::fscanf(f, "row_count=%zu", &n) != 1) {
        std::fprintf(stderr, "ERROR: Cannot parse row count from %s\n", path.c_str());
        std::fclose(f);
        std::exit(1);
    }
    std::fclose(f);
    return n;
}

// ---------------------------------------------------------------------------
// Raw memory-map
// ---------------------------------------------------------------------------
inline void* mmap_file_raw(const std::string& path, size_t& out_size) {
    int fd = ::open(path.c_str(), O_RDONLY);
    if (fd < 0) {
        std::fprintf(stderr, "ERROR: Cannot open %s\n", path.c_str());
        std::exit(1);
    }
    struct stat st;
    if (::fstat(fd, &st) < 0) {
        std::fprintf(stderr, "ERROR: fstat failed for %s\n", path.c_str());
        ::close(fd);
        std::exit(1);
    }
    out_size = static_cast<size_t>(st.st_size);
    if (out_size == 0) { ::close(fd); return nullptr; }
    void* p = ::mmap(nullptr, out_size, PROT_READ, MAP_PRIVATE, fd, 0);
    if (p == MAP_FAILED) {
        std::fprintf(stderr, "ERROR: mmap failed for %s (%zu bytes)\n",
                     path.c_str(), out_size);
        ::close(fd);
        std::exit(1);
    }
    ::close(fd);
    (void)::madvise(p, out_size, MADV_SEQUENTIAL);
    return p;
}

// ---------------------------------------------------------------------------
// Typed column mmap
// ---------------------------------------------------------------------------
template <typename T>
inline const T* mmap_column(const std::string& path, size_t expected_elems) {
    size_t sz = 0;
    void* p = mmap_file_raw(path, sz);
    if (sz < expected_elems * sizeof(T)) {
        std::fprintf(stderr, "ERROR: Column file %s too small: %zu < %zu bytes\n",
                     path.c_str(), sz, expected_elems * sizeof(T));
        std::exit(1);
    }
    return reinterpret_cast<const T*>(p);
}

// ---------------------------------------------------------------------------
// Variable-length string column (offsets.bin + data_data.bin)
// Storage format: offsets file has (n_rows + 1) uint32_t entries.
//   String for row i = data[offsets[i] .. offsets[i+1]).
// ---------------------------------------------------------------------------
struct VarlenColumn {
    const uint32_t* offsets = nullptr;  // n_rows + 1 entries
    const char*     data    = nullptr;  // contiguous byte pool
    size_t          data_size = 0;

    std::string_view get(size_t i) const {
        uint32_t s = offsets[i];
        uint32_t e = offsets[i + 1];
        return std::string_view(data + s, e - s);
    }
};

inline VarlenColumn mmap_varlen(const std::string& col_base_path, size_t /*n_rows*/) {
    VarlenColumn vc;
    size_t off_sz = 0, dat_sz = 0;
    vc.offsets   = reinterpret_cast<const uint32_t*>(
                       mmap_file_raw(col_base_path + ".bin", off_sz));
    vc.data      = reinterpret_cast<const char*>(
                       mmap_file_raw(col_base_path + "_data.bin", dat_sz));
    vc.data_size = dat_sz;
    return vc;
}

// ---------------------------------------------------------------------------
// Dictionary for dict-encoded uint8_t columns.
// Binary format: uint32_t count, then count × {uint16_t len, char[len]}.
// ---------------------------------------------------------------------------
struct Dictionary {
    uint32_t count = 0;
    std::vector<std::string> entries;

    void load(const std::string& path) {
        size_t sz = 0;
        const uint8_t* p = reinterpret_cast<const uint8_t*>(mmap_file_raw(path, sz));
        if (!p || sz < 4) return;
        count = *reinterpret_cast<const uint32_t*>(p);
        entries.resize(count);
        size_t pos = 4;
        for (uint32_t i = 0; i < count && pos + 2 <= sz; ++i) {
            uint16_t len = *reinterpret_cast<const uint16_t*>(p + pos);
            pos += 2;
            if (pos + len > sz) break;
            entries[i].assign(reinterpret_cast<const char*>(p + pos), len);
            pos += len;
        }
    }

    const std::string& get(uint8_t idx) const { return entries[idx]; }
};

} // namespace io
} // namespace mqo
